version: "3.4"

services:
  shop.api:
    build:
      context: ./src/Services/Shop/Shop.API
      dockerfile: Dockerfile.dev
    ports:
      - 8080:5000
    volumes:
      - ./src/Services/Shop/Shop.API/:/app
      - ./src/Services/Shop/Shop.API/bin
      - ./src/Services/Shop/Shop.API/obj

  shop.data:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_PASSWORD=abc123
      - POSTGRES_DB=shop
      - POSTGRES_HOST=shop.data
      - POSTGRES_PORT=5432
      - POSTGRES_USER=cloudcup